// <auto-generated />
using FinalProjectContemporaryProgramming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProjectContemporaryProgramming.Migrations
{
    [DbContext(typeof(FinalProjectContext))]
    partial class FinalProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProjectContemporaryProgramming.Models.GabesTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheGabeTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = "Jan 1, 1991",
                            CollegeProgram = "Information Technology",
                            FullName = "Gabe Newell",
                            YearInProgram = "3"
                        });
                });

            modelBuilder.Entity("FinalProjectContemporaryProgramming.Models.JohnsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteSport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteTVShow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteVideoGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheJohnsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteSport = "Handegg",
                            FavoriteTVShow = "The Wire",
                            FavoriteVideoGame = "Knights of the Old Republic II",
                            FirstName = "John",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("FinalProjectContemporaryProgramming.Models.MattsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteBreakfast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteDessert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteDinner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheMattsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteBreakfast = "Eggs and Ham",
                            FavoriteDessert = "Dessert Eggs",
                            FavoriteDinner = "Ham",
                            FirstName = "Matt",
                            LastName = "Caudill"
                        });
                });

            modelBuilder.Entity("FinalProjectContemporaryProgramming.Models.NicksTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IAmALiar")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheNicksTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteClass = "3",
                            FavoriteTa = "exampleTA",
                            FavoriteTeacher = "Information Technology",
                            FirstName = "Gabe",
                            IAmALiar = 1,
                            LastName = "Newell"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
